# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://gallavee.github.io/test1/"

git_url = "https://github.com/gallavee/test1/tree/main/"

def custom_doc_links(name): return None
